trigger:
  - production

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: patch
    value: 0

name: $(major).$(minor).$(patch)-$(Rev:r)

stages:
  - stage: assemble
    displayName: Assemble
    jobs:
      - job: build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Gradle@1
            displayName: Gradle Build
            inputs:
              jdkVersionOption: 1.11
  - stage: deploy
    displayName: Deploy
    dependsOn: assemble
    condition:
      not(eq(variables['build.reason'], 'PullRequest'))
    jobs:
      - job: deployToProduction
        displayName: Deploy to Production
        pool:
          vmImage: ubuntu-latest
        steps:
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: buildAndPush
              containerRegistry: SteeltoeContainerRegistry
              repository: initializr-config-server
              tags: |
                $(Build.BuildId)
                latest
          - task: KubernetesManifest@0
            displayName: Deploy to Production Cluster
            inputs:
              action: deploy
              kubernetesServiceConnection: SteeltoeProductionAKS
              manifests: deploy/kubernetes/manifest.yaml
              containers: steeltoe.azurecr.io/initializr-config-server:$(Build.BuildId)
              namespace: initializr
