trigger:
  - master

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: BuildArtifacts
    pool:
      vmImage: Ubuntu-16.04
    steps:
      - task: Gradle@1
        displayName: Build
        inputs:
          jdkVersionOption: 1.11
      - task: CloudFoundryCLIInstall@0
        displayName: Install CF CLI
        inputs:
          cfVersion: 6.51.0
      - task: CloudFoundry@1
        displayName: Push to Staging
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        inputs:
          cfEndpoint: PCFone
          skipSSLValidation: true
          org: group-steeltoe
          space: staging
          deploymentOptions: manifest
          cfManifest: deploy/cloud-foundry/manifest-Staging.yaml
          createServices: false
          bindServices: false
