trigger:
  - dev

variables:
  - name: major
    value: 0
  - name: minor
    value: 1
  - name: micro
    value: 0

name: $(major).$(minor).$(micro)-$(Rev:r)

jobs:
  - job: Build
    pool:
      vmImage: ubuntu-latest
    steps:
      - task: CloudFoundryCLIInstall@0
        displayName: Prep Cloud Foundry CLI
        inputs:
          cfVersion: 6.51.0
      - task: Gradle@1
        displayName: Gradle Build
        inputs:
          jdkVersionOption: 1.11
