server:
  port: 8888
spring:
  application:
    name: Steeltoe Initializr Config Server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/steeltoeoss-incubator/Steeltoe.Initializr.Configuration.git
logging:
  level:
    root: warn
    org.springframework.boot: info
    org.springframework.web: info
