server:
  port: 8888
spring:
  application:
    name: Steeltoe InitializrConfigServer
  cloud:
    config:
      server:
        git:
          uri: https://github.com/SteeltoeOSS/InitializrConfig
          default-label: main
  main:
    banner-mode: off
logging:
  level:
    root: warn
    io.steeltoe: info
    org.springframework: info
