---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: initializr-config-server
  namespace: initializr
spec:
  replicas: 2
  selector:
    matchLabels:
      app: initializr-config-server
  template:
    metadata:
      labels:
        app: initializr-config-server
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: initializr-config-server
        image: steeltoe.azurecr.io/initializr-config-server
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: initializr-config-server
  namespace: initializr
spec:
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: initializr-config-server
